import { Feedback } from './feedback.models';

export const FIRST_ROW_FEEDBACKS: Feedback[] = [
	{
		avatar: '1.webp',
		name: 'alex',
		date: '28.04.2024 18:30',
		content: 'great accounts, fast delivery',
	},
	{
		avatar: '2.webp',
		name: 'sceazr',
		date: '28.04.2024 13:50',
		content: 'Quick and smooth delivery!',
	},
	// {
	// 	avatar: '3.webp',
	// 	name: 'Magantosh1t',
	// 	date: '25.04.2024 13:59',
	// 	content: 'smooth delivery❤️',
	// },
	{
		avatar: '4.webp',
		name: 'evo',
		date: '24.04.2024 20:41',
		content: 'thank you guys for last minute accounts! ended up hitting Copa!',
	},
	{
		avatar: '5.webp',
		name: 'Preme',
		date: '24.04.2024 17:08',
		content: 'smooth delivery as always',
	},
	// {
	// 	avatar: '6.webp',
	// 	name: 'tobyy',
	// 	date: '23.04.2024 23:41',
	// 	content: 'everything good',
	// },
	// {
	// 	avatar: '7.webp',
	// 	name: 'shitty',
	// 	date: '22.04.2024 17:38',
	// 	content: 'fast delivery and nice customer service',
	// },
	{
		avatar: '8.webp',
		name: 'evo',
		date: '20.04.2024 1:34',
		content:
			'Extremely fast delivery & outstanding customer service...\n will definitely do business with again!',
	},
	// {
	// 	avatar: '9.webp',
	// 	name: 'Bzptiste.',
	// 	date: '18.04.2024 16:00',
	// 	content: 'Very good support thx!',
	// },
	{
		avatar: '10.webp',
		name: 'xander',
		date: '17.04.2024 17:40',
		content: 'Quick delivery and great accounts! thanks',
	},
	{
		avatar: '11.webp',
		name: 'REUMPS',
		date: '15.04.2024 16:19',
		content: 'Very good support thx!',
	},
	// {
	// 	avatar: '12.webp',
	// 	name: 'MerciLess',
	// 	date: '14.04.2024 16:26',
	// 	content: 'Under 24h delivery ! Very good support',
	// },
	{
		avatar: '13.webp',
		name: 'Tchipow',
		date: '14.04.2024 15:36',
		content: 'Fast delivery and very good support !',
	},
	// {
	// 	avatar: '14.webp',
	// 	name: 'ricko',
	// 	date: '13.04.2024 21:21',
	// 	content: 'Everything working great thanks to the amazing team',
	// },
	// {
	// 	avatar: '15.webp',
	// 	name: 'Chickenwing',
	// 	date: '24.03.2024 18:01',
	// 	content: 'Fast delivery and everything fine, ty',
	// },
	{
		avatar: '16.webp',
		name: 'pcook815',
		date: '20.03.2024 14:42',
		content: 'aged accts legit, appreciate the quick replies/support',
	},
	{
		avatar: '17.webp',
		name: 'kirk',
		date: '19.03.2024 8:15',
		content: 'definitely recommend!',
	},
	{
		avatar: '18.webp',
		name: 'kowalski3073',
		date: '15.03.2024 20:52',
		content: 'accounts working and fast delivery!',
	},
	// {
	// 	avatar: '19.webp',
	// 	name: 'veryname',
	// 	content: 'Accs working, fast delivery 🔥',
	// 	date: '13.03.2024 14:52',
	// },
	{
		avatar: '20.webp',
		name: 'Blake',
		date: '12.03.2024 21:49',
		content: 'Very quick turnaround from the guys, excellent service',
	},
	// {
	// 	avatar: '21.webp',
	// 	name: 'Dave',
	// 	date: '05.03.2024 21:51',
	// 	content:
	// 		'Exactly what I asked for and been helpful throughout the process. \nEspecially fast delivery this time around! Thanks',
	// },
	{
		avatar: '22.webp',
		name: 'sceazr',
		date: '03.03.2024 19:19',
		content: 'The accounts work and very helpful service',
	},
	{
		avatar: '23.webp',
		name: 'Mamba',
		date: '27.02.2024 23:37',
		content: 'accounts work, great service!',
	},
	// {
	// 	avatar: '24.webp',
	// 	name: 'maya',
	// 	date: '19.02.2024 17:29',
	// 	content: 'accounts looks good and helpful',
	// },
	{
		avatar: '25.webp',
		name: 'dome',
		date: '02.02.2024 19:26',
		content: 'Super quick delivery times and great accounts, definitely recommend!',
	},
	// {
	// 	avatar: '26.webp',
	// 	name: 'Jae',
	// 	date: '01.02.2024 19:31',
	// 	content: 'Fast delivery and good quality account 🔥',
	// },
	{
		avatar: '27.webp',
		name: 'Scheme',
		date: '01.02.2024 9:17',
		content: 'Fast delivery again. They do not miss 🔥',
	},
	// {
	// 	avatar: '28.webp',
	// 	name: 'bando',
	// 	date: '01.02.2024 2:04',
	// 	content: 'Quick and reliable order. Accounts are legit and not bottom tier.',
	// },
	// {
	// 	avatar: '29.webp',
	// 	name: 'Scheme',
	// 	date: '24.01.2024 20:29',
	// 	content: 'fast delivery + helpful',
	// },
];

export const SECOND_ROW_FEEDBACKS: Feedback[] = [
	{
		avatar: '30.webp',
		name: 'UofODuck',
		date: '24.01.2024 17:26',
		content: 'Quick and reliable order.',
	},
	{
		avatar: '31.webp',
		name: 'Bones',
		date: '23.01.2024 22:42',
		content: 'quick reliable service',
	},
	{
		avatar: '32.webp',
		name: 'bando',
		date: '23.01.2024 22:41',
		content: 'Quick (5-7 days turnaround) and efficient process. No issues with delivery.',
	},
	{
		avatar: '33.webp',
		name: 'THEiSH',
		date: '22.01.2024 23:40',
		content: 'friendly service, thank you ❤️',
	},
	// {
	// 	avatar: '34.webp',
	// 	name: 'bjevryday',
	// 	date: '22.01.2024 19:38',
	// 	content:
	// 		'Made an original order of 250 acts, and when 9 of them had an incorrect password, \nthey replaced them quickly and efficiently 👍🏾',
	// },
	{
		avatar: '35.webp',
		name: 'TAYLOR SWIFT <33',
		date: '18.01.2024 5:52',
		content: 'Legit services, sent me my accounts Quickly, recommend!',
	},
	{
		avatar: '36.webp',
		name: 'dirtykev',
		date: '18.01.2024 3:16',
		content: 'legit services appreciate it',
	},
	// {
	// 	avatar: '37.webp',
	// 	name: 'UofODuck',
	// 	date: '17.01.2024 19:35',
	// 	content:
	// 		'Quick and efficient process. No issues with delivery. \nAccounts seem to be in working order. Would order again.',
	// },
	// {
	// 	avatar: '38.webp',
	// 	name: 'Jay-W',
	// 	date: '18.01.2024 2:25',
	// 	content: 'Quick delivery, gonna test and see how it goes',
	// },
	// {
	// 	avatar: '39.webp',
	// 	name: 'Perry',
	// 	date: '16.01.2024 12:43',
	// 	content: 'Thank you!!',
	// },
	// {
	// 	avatar: '40.webp',
	// 	name: 'skipper',
	// 	date: '05.01.2024 18:50',
	// 	content: 'everything is great, advise!',
	// },
	// {
	// 	avatar: '41.webp',
	// 	name: 'Lyova',
	// 	date: '02.01.2024 15:34',
	// 	content: 'Smooth and quick!',
	// },
	// {
	// 	avatar: '42.webp',
	// 	name: 'bklove',
	// 	date: '29.12.2023 6:39',
	// 	content: 'Delivery for aged acc was super fast!!! DEF RECOMMEND!',
	// },
	// {
	// 	avatar: '43.webp',
	// 	name: 'bjevryday',
	// 	date: '28.12.2023 9:11',
	// 	content:
	// 		'Delivery is supposed to be 3-4 days, got my order with a bit over a week delay.\n No big deal, customer service is good and spreadsheet is professional and complete.',
	// },
	{
		avatar: '44.webp',
		name: 'Uttam',
		date: '25.12.2023 12:55',
		content: 'very smooth transaction',
	},
	{
		avatar: '45.webp',
		name: 'charlie914',
		date: '25.12.2023 8:50',
		content: 'got my aged TM accounts!',
	},
	// {
	// 	avatar: '46.webp',
	// 	name: 'misdah',
	// 	date: '07.12.2023 9:53',
	// 	content: 'quick deliver, very supportive and reactive, just perfect',
	// },
	// {
	// 	avatar: '47.webp',
	// 	name: 'Shiba',
	// 	date: '03.12.2023 11:35',
	// 	content: 'Quick deliver / organized will purchase again',
	// },
	// {
	// 	avatar: '48.webp',
	// 	name: 'frueh',
	// 	date: '20.11.2023 15:45',
	// 	content: 'quick deliver, smooth and helpful guides',
	// },
	// {
	// 	avatar: '49.webp',
	// 	name: 'ksa',
	// 	date: '17.11.2023 13:11',
	// 	content: 'order delivered quickly',
	// },
	// {
	// 	avatar: '50.webp',
	// 	name: 'Shep',
	// 	date: '16.11.2023 15:11',
	// 	content: 'Got TM US aged accs, smooth and fast service, thanks',
	// },
	{
		avatar: '51.webp',
		name: 'Sebi',
		date: '04.11.2023 12:03',
		content: 'All good again (gmails)',
	},
	{
		avatar: '52.webp',
		name: 'ko',
		date: '02.11.2023 1:47',
		content: 'great service and fast!',
	},
	{
		avatar: '53.webp',
		name: 'Cold Winters',
		date: '31.10.2023 23:43',
		content: 'Great service, would definitely recommend to those that are looking to buy',
	},
	{
		avatar: '54.webp',
		name: 'Devin',
		date: '29.10.2023 23:41',
		content: 'great service!',
	},
	{
		avatar: '55.webp',
		name: 'mtx',
		date: '29.10.2023 1:14',
		content: 'Professional and fast service',
	},
];
