import { ProductItem } from '../models/product-item.models';
import { SITE_URL } from './env.consts';

export const PRODUCT_ITEMS: ProductItem[] = [
	{
		id: 'tm-1',
		img: SITE_URL + '/assets/products/tm-1.webp',
		name: 'Ticketmaster',
		description: 'aged accounts',
		nameForWh: 'Ticketmaster regular',
		price: 4.9,
		per: 1,
		features: [
			'Age 2002-2018',
			'Forwarding included',
			'Full email access',
			'Better place in queue',
			'Untested accounts ONLY',
			'1 month guarantee',
		],
		goalName: 'form_submit_ticketmaster_aged_account',
		openFormGoalName: 'click_purchase_tm_aged',
	},
	{
		id: 'tm-2',
		img: SITE_URL + '/assets/products/tm-2.webp',
		name: 'Ticketmaster',
		nameForWh: 'Ticketmaster history',
		description: 'Accounts with history',
		price: 8.9,
		per: 1,
		features: [
			'Age 2002-2018',
			'Forwarding included',
			'Full email access',
			'Random orders amount',
			'Untested accounts ONLY',
			'1 month guarantee',
		],
		goalName: 'form_submit_ticketmaster_account_with_history',
		openFormGoalName: 'click_purchase_tm_history',
	},
	{
		id: 'gmail-1',
		img: SITE_URL + '/assets/products/gmail.webp',
		name: 'GMAIL',
		description: 'Forwarded',
		price: 0.899,
		per: 100,
		features: [
			'Age 1 month+',
			'Mixed regions',
			'With 2FA security',
			'Full email access',
			'Fwd to hotmail',
			'1 month guarantee',
		],
		goalName: 'form_submit_gmail',
		openFormGoalName: 'click_purchase_gmail',
		sold: true,
	},
	{
		id: 'hotmail-1',
		img: SITE_URL + '/assets/products/hotmail.webp',
		name: 'HOTMAIL',
		description: 'Forwarded',
		price: 0.199,
		per: 100,
		features: [
			'Age 1 month+',
			'Mixed regions',
			'With 2FA security',
			'Full email access',
			'Fwd to your email / domain',
			'1 month guarantee',
		],
		goalName: 'form_submit_hotmail',
		openFormGoalName: 'click_purchase_hotmail',
	},
];
